"use strict";

// generated on Mon Jun 20 10:27:07 CEST 2016

var heroes = {
    abaddon: new Env({
        "str_gain": 2.7,
        "hp_regen": 0.25,
        "agi": 17,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 2,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 310,
        "int": 21,
        "mp_regen_base": 0.01,
        "agi_gain": 1.5,
        "str": 23,
        "abilities": [
            "abaddon_death_coil",
            "abaddon_aphotic_shield",
            "abaddon_frostmourne",
            "abaddon_borrowed_time",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Abaddon",
        "attack_damage_base": 37,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    alchemist: new Env({
        "str_gain": 1.8,
        "hp_regen": 0.25,
        "agi": 11,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.8,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 295,
        "int": 25,
        "mp_regen_base": 0.01,
        "agi_gain": 1.2,
        "str": 25,
        "abilities": [
            "alchemist_acid_spray",
            "alchemist_unstable_concoction",
            "alchemist_goblins_greed",
            "alchemist_chemical_rage",
            "alchemist_unstable_concoction_throw",
            "attribute_bonus"
        ],
        "armor": 0,
        "attack_speed_hero": 100,
        "name": "Alchemist",
        "attack_damage_base": 28.5,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    ancient_apparition: new Env({
        "str_gain": 1.4,
        "hp_regen": 0.25,
        "agi": 20,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.6,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 295,
        "int": 25,
        "mp_regen_base": 0.01,
        "agi_gain": 2.2,
        "str": 18,
        "abilities": [
            "ancient_apparition_cold_feet",
            "ancient_apparition_ice_vortex",
            "ancient_apparition_chilling_touch",
            "ancient_apparition_ice_blast",
            "ancient_apparition_ice_blast_release",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Ancient Apparition",
        "attack_damage_base": 24,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    antimage: new Env({
        "str_gain": 1.2,
        "hp_regen": 0.25,
        "agi": 22,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.8,
        "primary_attribute": "agi",
        "is_melee": 1,
        "movement_speed": 315,
        "int": 15,
        "mp_regen_base": 0.01,
        "agi_gain": 2.8,
        "str": 22,
        "abilities": [
            "antimage_mana_break",
            "antimage_blink",
            "antimage_spell_shield",
            "antimage_mana_void",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Anti-Mage",
        "attack_damage_base": 29,
        "movement_speed_max": 522,
        "base_attack_time": 1.45,
        "vulnerability_mag": 0.75
    }),
    arc_warden: new Env({
        "str_gain": 2.3,
        "hp_regen": 0.25,
        "agi": 15,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.6,
        "primary_attribute": "agi",
        "is_melee": 0,
        "movement_speed": 295,
        "int": 24,
        "mp_regen_base": 0.01,
        "agi_gain": 1.8,
        "str": 24,
        "abilities": [
            "arc_warden_flux",
            "arc_warden_magnetic_field",
            "arc_warden_spark_wraith",
            "arc_warden_tempest_double",
            "attribute_bonus"
        ],
        "armor": -2,
        "attack_speed_hero": 100,
        "name": "Arc Warden",
        "attack_damage_base": 34,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    axe: new Env({
        "str_gain": 2.5,
        "hp_regen": 3,
        "agi": 20,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.6,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 290,
        "int": 18,
        "mp_regen_base": 0.01,
        "agi_gain": 2.2,
        "str": 25,
        "abilities": [
            "axe_berserkers_call",
            "axe_battle_hunger",
            "axe_counter_helix",
            "axe_culling_blade",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Axe",
        "attack_damage_base": 26,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    bane: new Env({
        "str_gain": 2.1,
        "hp_regen": 0.25,
        "agi": 22,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.1,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 310,
        "int": 22,
        "mp_regen_base": 0.01,
        "agi_gain": 2.1,
        "str": 22,
        "abilities": [
            "bane_enfeeble",
            "bane_brain_sap",
            "bane_nightmare",
            "bane_fiends_grip",
            "bane_nightmare_end",
            "attribute_bonus"
        ],
        "armor": 1,
        "attack_speed_hero": 100,
        "name": "Bane",
        "attack_damage_base": 36,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    batrider: new Env({
        "str_gain": 2.4,
        "hp_regen": 2,
        "agi": 15,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.5,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 290,
        "int": 24,
        "mp_regen_base": 0.01,
        "agi_gain": 1.5,
        "str": 23,
        "abilities": [
            "batrider_sticky_napalm",
            "batrider_flamebreak",
            "batrider_firefly",
            "batrider_flaming_lasso",
            "attribute_bonus"
        ],
        "armor": 0,
        "attack_speed_hero": 100,
        "name": "Batrider",
        "attack_damage_base": 16,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    beastmaster: new Env({
        "str_gain": 2.2,
        "hp_regen": 0.25,
        "agi": 18,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.9,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 310,
        "int": 16,
        "mp_regen_base": 0.01,
        "agi_gain": 1.6,
        "str": 23,
        "abilities": [
            "beastmaster_wild_axes",
            "beastmaster_call_of_the_wild",
            "beastmaster_call_of_the_wild_boar",
            "beastmaster_inner_beast",
            "beastmaster_primal_roar",
            "attribute_bonus"
        ],
        "armor": 2,
        "attack_speed_hero": 100,
        "name": "Beastmaster",
        "attack_damage_base": 43,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    bloodseeker: new Env({
        "str_gain": 2.4,
        "hp_regen": 0.25,
        "agi": 24,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.7,
        "primary_attribute": "agi",
        "is_melee": 1,
        "movement_speed": 290,
        "int": 18,
        "mp_regen_base": 0.01,
        "agi_gain": 3,
        "str": 23,
        "abilities": [
            "bloodseeker_bloodrage",
            "bloodseeker_blood_bath",
            "bloodseeker_thirst",
            "bloodseeker_rupture",
            "attribute_bonus"
        ],
        "armor": 0,
        "attack_speed_hero": 100,
        "name": "Bloodseeker",
        "attack_damage_base": 32,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    bounty_hunter: new Env({
        "str_gain": 1.8,
        "hp_regen": 0.75,
        "agi": 21,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 2,
        "primary_attribute": "agi",
        "is_melee": 1,
        "movement_speed": 315,
        "int": 19,
        "mp_regen_base": 0.01,
        "agi_gain": 3,
        "str": 17,
        "abilities": [
            "bounty_hunter_shuriken_toss",
            "bounty_hunter_jinada",
            "bounty_hunter_wind_walk",
            "bounty_hunter_track",
            "attribute_bonus"
        ],
        "armor": 3,
        "attack_speed_hero": 100,
        "name": "Bounty Hunter",
        "attack_damage_base": 31,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    brewmaster: new Env({
        "str_gain": 2.9,
        "hp_regen": 0.75,
        "agi": 22,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.25,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 300,
        "int": 14,
        "mp_regen_base": 0.01,
        "agi_gain": 1.95,
        "str": 23,
        "abilities": [
            "brewmaster_thunder_clap",
            "brewmaster_drunken_haze",
            "brewmaster_drunken_brawler",
            "brewmaster_primal_split",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Brewmaster",
        "attack_damage_base": 32.5,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    bristleback: new Env({
        "str_gain": 2.2,
        "hp_regen": 0.25,
        "agi": 17,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 2.8,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 290,
        "int": 14,
        "mp_regen_base": 0.01,
        "agi_gain": 1.8,
        "str": 22,
        "abilities": [
            "bristleback_viscous_nasal_goo",
            "bristleback_quill_spray",
            "bristleback_bristleback",
            "bristleback_warpath",
            "attribute_bonus"
        ],
        "armor": 1,
        "attack_speed_hero": 100,
        "name": "Bristleback",
        "attack_damage_base": 31,
        "movement_speed_max": 522,
        "base_attack_time": 1.8,
        "vulnerability_mag": 0.75
    }),
    broodmother: new Env({
        "str_gain": 2.5,
        "hp_regen": 0.25,
        "agi": 18,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 2,
        "primary_attribute": "agi",
        "is_melee": 1,
        "movement_speed": 295,
        "int": 18,
        "mp_regen_base": 0.01,
        "agi_gain": 2.2,
        "str": 17,
        "abilities": [
            "broodmother_spawn_spiderlings",
            "broodmother_spin_web",
            "broodmother_incapacitating_bite",
            "broodmother_insatiable_hunger",
            "attribute_bonus"
        ],
        "armor": 0,
        "attack_speed_hero": 100,
        "name": "Broodmother",
        "attack_damage_base": 29,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    centaur: new Env({
        "str_gain": 4,
        "hp_regen": 0.25,
        "agi": 15,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.6,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 300,
        "int": 15,
        "mp_regen_base": 0.01,
        "agi_gain": 2,
        "str": 23,
        "abilities": [
            "centaur_hoof_stomp",
            "centaur_double_edge",
            "centaur_return",
            "centaur_stampede",
            "attribute_bonus"
        ],
        "armor": 1,
        "attack_speed_hero": 100,
        "name": "Centaur Warrunner",
        "attack_damage_base": 33,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    chaos_knight: new Env({
        "str_gain": 2.9,
        "hp_regen": 0.25,
        "agi": 14,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.2,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 325,
        "int": 16,
        "mp_regen_base": 0.01,
        "agi_gain": 2.1,
        "str": 20,
        "abilities": [
            "chaos_knight_chaos_bolt",
            "chaos_knight_reality_rift",
            "chaos_knight_chaos_strike",
            "chaos_knight_phantasm",
            "attribute_bonus"
        ],
        "armor": 2,
        "attack_speed_hero": 100,
        "name": "Chaos Knight",
        "attack_damage_base": 44,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    chen: new Env({
        "str_gain": 1.5,
        "hp_regen": 0.25,
        "agi": 15,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.8,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 300,
        "int": 21,
        "mp_regen_base": 0.01,
        "agi_gain": 2.1,
        "str": 23,
        "abilities": [
            "chen_penitence",
            "chen_test_of_faith",
            "chen_test_of_faith_teleport",
            "chen_holy_persuasion",
            "chen_hand_of_god",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Chen",
        "attack_damage_base": 27,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    clinkz: new Env({
        "str_gain": 1.6,
        "hp_regen": 0.25,
        "agi": 22,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 1.55,
        "primary_attribute": "agi",
        "is_melee": 0,
        "movement_speed": 300,
        "int": 16,
        "mp_regen_base": 0.01,
        "agi_gain": 3.3,
        "str": 15,
        "abilities": [
            "clinkz_strafe",
            "clinkz_searing_arrows",
            "clinkz_wind_walk",
            "clinkz_death_pact",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Clinkz",
        "attack_damage_base": 18,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    rattletrap: new Env({
        "str_gain": 2.9,
        "hp_regen": 0.25,
        "agi": 13,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.3,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 315,
        "int": 17,
        "mp_regen_base": 0.01,
        "agi_gain": 2.3,
        "str": 24,
        "abilities": [
            "rattletrap_battery_assault",
            "rattletrap_power_cogs",
            "rattletrap_rocket_flare",
            "rattletrap_hookshot",
            "attribute_bonus"
        ],
        "armor": 0,
        "attack_speed_hero": 100,
        "name": "Clockwerk",
        "attack_damage_base": 32,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    crystal_maiden: new Env({
        "str_gain": 1.7,
        "hp_regen": 0.25,
        "agi": 16,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.9,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 280,
        "int": 16,
        "mp_regen_base": 0.01,
        "agi_gain": 1.6,
        "str": 16,
        "abilities": [
            "crystal_maiden_crystal_nova",
            "crystal_maiden_frostbite",
            "crystal_maiden_brilliance_aura",
            "crystal_maiden_freezing_field",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Crystal Maiden",
        "attack_damage_base": 22,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    dark_seer: new Env({
        "str_gain": 2.3,
        "hp_regen": 0.25,
        "agi": 12,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 2.7,
        "primary_attribute": "int",
        "is_melee": 1,
        "movement_speed": 300,
        "int": 25,
        "mp_regen_base": 0.01,
        "agi_gain": 1.2,
        "str": 22,
        "abilities": [
            "dark_seer_vacuum",
            "dark_seer_ion_shell",
            "dark_seer_surge",
            "dark_seer_wall_of_replica",
            "attribute_bonus"
        ],
        "armor": 5,
        "attack_speed_hero": 100,
        "name": "Dark Seer",
        "attack_damage_base": 34,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    dazzle: new Env({
        "str_gain": 1.85,
        "hp_regen": 0.25,
        "agi": 21,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 3.4,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 305,
        "int": 27,
        "mp_regen_base": 0.01,
        "agi_gain": 1.7,
        "str": 16,
        "abilities": [
            "dazzle_poison_touch",
            "dazzle_shallow_grave",
            "dazzle_shadow_wave",
            "dazzle_weave",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Dazzle",
        "attack_damage_base": 23,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    death_prophet: new Env({
        "str_gain": 1.9,
        "hp_regen": 0.75,
        "agi": 14,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 3,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 310,
        "int": 23,
        "mp_regen_base": 0.01,
        "agi_gain": 1.4,
        "str": 18,
        "abilities": [
            "death_prophet_carrion_swarm",
            "death_prophet_silence",
            "death_prophet_spirit_siphon",
            "death_prophet_exorcism",
            "attribute_bonus"
        ],
        "armor": 1,
        "attack_speed_hero": 100,
        "name": "Death Prophet",
        "attack_damage_base": 30,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    disruptor: new Env({
        "str_gain": 1.9,
        "hp_regen": 0.25,
        "agi": 15,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.5,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 300,
        "int": 22,
        "mp_regen_base": 0.01,
        "agi_gain": 1.4,
        "str": 19,
        "abilities": [
            "disruptor_thunder_strike",
            "disruptor_glimpse",
            "disruptor_kinetic_field",
            "disruptor_static_storm",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Disruptor",
        "attack_damage_base": 29,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    doom_bringer: new Env({
        "str_gain": 3.2,
        "hp_regen": 0.25,
        "agi": 11,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 2.1,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 290,
        "int": 13,
        "mp_regen_base": 0.01,
        "agi_gain": 0.9,
        "str": 26,
        "abilities": [
            "doom_bringer_devour",
            "doom_bringer_scorched_earth",
            "doom_bringer_infernal_blade",
            "doom_bringer_doom",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Doom",
        "attack_damage_base": 35,
        "movement_speed_max": 522,
        "base_attack_time": 2,
        "vulnerability_mag": 0.75
    }),
    dragon_knight: new Env({
        "str_gain": 2.8,
        "hp_regen": 0.25,
        "agi": 19,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.7,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 290,
        "int": 15,
        "mp_regen_base": 0.01,
        "agi_gain": 2.2,
        "str": 19,
        "abilities": [
            "dragon_knight_breathe_fire",
            "dragon_knight_dragon_tail",
            "dragon_knight_dragon_blood",
            "dragon_knight_elder_dragon_form",
            "attribute_bonus"
        ],
        "armor": 1,
        "attack_speed_hero": 100,
        "name": "Dragon Knight",
        "attack_damage_base": 34,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    drow_ranger: new Env({
        "str_gain": 1.9,
        "hp_regen": 0.25,
        "agi": 26,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 1.4,
        "primary_attribute": "agi",
        "is_melee": 0,
        "movement_speed": 300,
        "int": 15,
        "mp_regen_base": 0.01,
        "agi_gain": 1.9,
        "str": 17,
        "abilities": [
            "drow_ranger_frost_arrows",
            "drow_ranger_wave_of_silence",
            "drow_ranger_trueshot",
            "drow_ranger_marksmanship",
            "attribute_bonus"
        ],
        "armor": -3,
        "attack_speed_hero": 100,
        "name": "Drow Ranger",
        "attack_damage_base": 23.5,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    earth_spirit: new Env({
        "str_gain": 2.9,
        "hp_regen": 0.25,
        "agi": 17,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 2.1,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 295,
        "int": 18,
        "mp_regen_base": 0.01,
        "agi_gain": 1.5,
        "str": 21,
        "abilities": [
            "earth_spirit_boulder_smash",
            "earth_spirit_rolling_boulder",
            "earth_spirit_geomagnetic_grip",
            "earth_spirit_stone_caller",
            "earth_spirit_petrify",
            "earth_spirit_magnetize",
            "attribute_bonus"
        ],
        "armor": 1,
        "attack_speed_hero": 100,
        "name": "Earth Spirit",
        "attack_damage_base": 30,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    earthshaker: new Env({
        "str_gain": 2.9,
        "hp_regen": 0.25,
        "agi": 12,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.8,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 310,
        "int": 16,
        "mp_regen_base": 0.01,
        "agi_gain": 1.4,
        "str": 22,
        "abilities": [
            "earthshaker_fissure",
            "earthshaker_enchant_totem",
            "earthshaker_aftershock",
            "earthshaker_echo_slam",
            "attribute_bonus"
        ],
        "armor": 1,
        "attack_speed_hero": 100,
        "name": "Earthshaker",
        "attack_damage_base": 29,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    elder_titan: new Env({
        "str_gain": 2.3,
        "hp_regen": 0.25,
        "agi": 14,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.6,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 315,
        "int": 23,
        "mp_regen_base": 0.01,
        "agi_gain": 1.5,
        "str": 24,
        "abilities": [
            "elder_titan_echo_stomp",
            "elder_titan_ancestral_spirit",
            "elder_titan_natural_order",
            "elder_titan_return_spirit",
            "elder_titan_earth_splitter",
            "attribute_bonus"
        ],
        "armor": 1,
        "attack_speed_hero": 100,
        "name": "Elder Titan",
        "attack_damage_base": 28,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    ember_spirit: new Env({
        "str_gain": 2,
        "hp_regen": 0.75,
        "agi": 22,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.8,
        "primary_attribute": "agi",
        "is_melee": 1,
        "movement_speed": 310,
        "int": 20,
        "mp_regen_base": 0.01,
        "agi_gain": 1.8,
        "str": 19,
        "abilities": [
            "ember_spirit_searing_chains",
            "ember_spirit_sleight_of_fist",
            "ember_spirit_flame_guard",
            "ember_spirit_activate_fire_remnant",
            "ember_spirit_fire_remnant",
            "attribute_bonus"
        ],
        "armor": -2,
        "attack_speed_hero": 100,
        "name": "Ember Spirit",
        "attack_damage_base": 32,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    enchantress: new Env({
        "str_gain": 1,
        "hp_regen": 0.25,
        "agi": 19,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.8,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 335,
        "int": 16,
        "mp_regen_base": 0.01,
        "agi_gain": 1.8,
        "str": 16,
        "abilities": [
            "enchantress_untouchable",
            "enchantress_enchant",
            "enchantress_natures_attendants",
            "enchantress_impetus",
            "attribute_bonus"
        ],
        "armor": -2,
        "attack_speed_hero": 100,
        "name": "Enchantress",
        "attack_damage_base": 36,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    enigma: new Env({
        "str_gain": 2.1,
        "hp_regen": 0.25,
        "agi": 14,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 3.4,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 300,
        "int": 20,
        "mp_regen_base": 0.01,
        "agi_gain": 1,
        "str": 17,
        "abilities": [
            "enigma_malefice",
            "enigma_demonic_conversion",
            "enigma_midnight_pulse",
            "enigma_black_hole",
            "attribute_bonus"
        ],
        "armor": 2,
        "attack_speed_hero": 100,
        "name": "Enigma",
        "attack_damage_base": 25,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    faceless_void: new Env({
        "str_gain": 1.8,
        "hp_regen": 0.75,
        "agi": 23,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.5,
        "primary_attribute": "agi",
        "is_melee": 1,
        "movement_speed": 300,
        "int": 15,
        "mp_regen_base": 0.01,
        "agi_gain": 2.65,
        "str": 23,
        "abilities": [
            "faceless_void_time_walk",
            "faceless_void_time_dilation",
            "faceless_void_time_lock",
            "faceless_void_chronosphere",
            "attribute_bonus"
        ],
        "armor": 1,
        "attack_speed_hero": 100,
        "name": "Faceless Void",
        "attack_damage_base": 40,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    gyrocopter: new Env({
        "str_gain": 1.8,
        "hp_regen": 0.25,
        "agi": 24,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.1,
        "primary_attribute": "agi",
        "is_melee": 0,
        "movement_speed": 315,
        "int": 19,
        "mp_regen_base": 0.01,
        "agi_gain": 2.8,
        "str": 18,
        "abilities": [
            "gyrocopter_rocket_barrage",
            "gyrocopter_homing_missile",
            "gyrocopter_flak_cannon",
            "gyrocopter_call_down",
            "attribute_bonus"
        ],
        "armor": 1,
        "attack_speed_hero": 100,
        "name": "Gyrocopter",
        "attack_damage_base": 18,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    huskar: new Env({
        "str_gain": 2.4,
        "hp_regen": 0.25,
        "agi": 15,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 1.5,
        "primary_attribute": "str",
        "is_melee": 0,
        "movement_speed": 300,
        "int": 18,
        "mp_regen_base": 0.01,
        "agi_gain": 1.4,
        "str": 21,
        "abilities": [
            "huskar_inner_vitality",
            "huskar_burning_spear",
            "huskar_berserkers_blood",
            "huskar_life_break",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Huskar",
        "attack_damage_base": 25.5,
        "movement_speed_max": 522,
        "base_attack_time": 1.6,
        "vulnerability_mag": 0.75
    }),
    invoker: new Env({
        "str_gain": 1.7,
        "hp_regen": 0.25,
        "agi": 14,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 4,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 280,
        "int": 16,
        "mp_regen_base": 0.01,
        "agi_gain": 1.9,
        "str": 17,
        "abilities": [
            "invoker_quas",
            "invoker_wex",
            "invoker_exort",
            "invoker_invoke",
            "invoker_cold_snap",
            "invoker_ghost_walk",
            "invoker_tornado",
            "invoker_emp",
            "invoker_alacrity",
            "invoker_chaos_meteor",
            "invoker_sun_strike",
            "invoker_forge_spirit",
            "invoker_ice_wall",
            "invoker_deafening_blast",
            "invoker_attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Invoker",
        "attack_damage_base": 22,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    wisp: new Env({
        "str_gain": 1.9,
        "hp_regen": 0.25,
        "agi": 14,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 1.7,
        "primary_attribute": "str",
        "is_melee": 0,
        "movement_speed": 295,
        "int": 23,
        "mp_regen_base": 0.01,
        "agi_gain": 1.6,
        "str": 17,
        "abilities": [
            "wisp_tether",
            "wisp_tether_break",
            "wisp_spirits",
            "wisp_overcharge",
            "wisp_relocate",
            "wisp_spirits_in",
            "wisp_spirits_out",
            "attribute_bonus"
        ],
        "armor": -2,
        "attack_speed_hero": 100,
        "name": "Io",
        "attack_damage_base": 30.5,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    jakiro: new Env({
        "str_gain": 2.3,
        "hp_regen": 0.25,
        "agi": 10,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.8,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 290,
        "int": 28,
        "mp_regen_base": 0.01,
        "agi_gain": 1.2,
        "str": 25,
        "abilities": [
            "jakiro_dual_breath",
            "jakiro_ice_path",
            "jakiro_liquid_fire",
            "jakiro_macropyre",
            "attribute_bonus"
        ],
        "armor": 1,
        "attack_speed_hero": 100,
        "name": "Jakiro",
        "attack_damage_base": 29,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    juggernaut: new Env({
        "str_gain": 1.9,
        "hp_regen": 0.75,
        "agi": 26,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.4,
        "primary_attribute": "agi",
        "is_melee": 1,
        "movement_speed": 305,
        "int": 14,
        "mp_regen_base": 0.01,
        "agi_gain": 2.4,
        "str": 20,
        "abilities": [
            "juggernaut_blade_fury",
            "juggernaut_healing_ward",
            "juggernaut_blade_dance",
            "juggernaut_omni_slash",
            "attribute_bonus"
        ],
        "armor": 0,
        "attack_speed_hero": 100,
        "name": "Juggernaut",
        "attack_damage_base": 26,
        "movement_speed_max": 522,
        "base_attack_time": 1.4,
        "vulnerability_mag": 0.75
    }),
    keeper_of_the_light: new Env({
        "str_gain": 1.8,
        "hp_regen": 0.25,
        "agi": 15,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.8,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 335,
        "int": 25,
        "mp_regen_base": 0.01,
        "agi_gain": 1.6,
        "str": 14,
        "abilities": [
            "keeper_of_the_light_illuminate",
            "keeper_of_the_light_mana_leak",
            "keeper_of_the_light_chakra_magic",
            "keeper_of_the_light_recall",
            "keeper_of_the_light_blinding_light",
            "keeper_of_the_light_spirit_form",
            "keeper_of_the_light_illuminate_end",
            "keeper_of_the_light_spirit_form_illuminate",
            "keeper_of_the_light_spirit_form_illuminate_end",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Keeper of the Light",
        "attack_damage_base": 25,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    kunkka: new Env({
        "str_gain": 3,
        "hp_regen": 0.25,
        "agi": 14,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.5,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 300,
        "int": 18,
        "mp_regen_base": 0.01,
        "agi_gain": 1.3,
        "str": 24,
        "abilities": [
            "kunkka_torrent",
            "kunkka_tidebringer",
            "kunkka_x_marks_the_spot",
            "kunkka_ghostship",
            "kunkka_return",
            "attribute_bonus"
        ],
        "armor": 2,
        "attack_speed_hero": 100,
        "name": "Kunkka",
        "attack_damage_base": 31,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    legion_commander: new Env({
        "str_gain": 2.6,
        "hp_regen": 0.25,
        "agi": 18,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 2.2,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 320,
        "int": 20,
        "mp_regen_base": 0.01,
        "agi_gain": 1.7,
        "str": 26,
        "abilities": [
            "legion_commander_overwhelming_odds",
            "legion_commander_press_the_attack",
            "legion_commander_moment_of_courage",
            "legion_commander_duel",
            "attribute_bonus"
        ],
        "armor": 0,
        "attack_speed_hero": 100,
        "name": "Legion Commander",
        "attack_damage_base": 37,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    leshrac: new Env({
        "str_gain": 1.5,
        "hp_regen": 0.25,
        "agi": 23,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 3,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 320,
        "int": 26,
        "mp_regen_base": 0.01,
        "agi_gain": 1.7,
        "str": 16,
        "abilities": [
            "leshrac_split_earth",
            "leshrac_diabolic_edict",
            "leshrac_lightning_storm",
            "leshrac_pulse_nova",
            "attribute_bonus"
        ],
        "armor": 0,
        "attack_speed_hero": 100,
        "name": "Leshrac",
        "attack_damage_base": 17,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    lich: new Env({
        "str_gain": 1.55,
        "hp_regen": 0.25,
        "agi": 15,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 3.25,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 315,
        "int": 18,
        "mp_regen_base": 0.01,
        "agi_gain": 2,
        "str": 18,
        "abilities": [
            "lich_frost_nova",
            "lich_frost_armor",
            "lich_dark_ritual",
            "lich_chain_frost",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Lich",
        "attack_damage_base": 28.5,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    life_stealer: new Env({
        "str_gain": 3,
        "hp_regen": 0.25,
        "agi": 18,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.75,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 315,
        "int": 15,
        "mp_regen_base": 0.01,
        "agi_gain": 1.9,
        "str": 25,
        "abilities": [
            "life_stealer_rage",
            "life_stealer_feast",
            "life_stealer_open_wounds",
            "life_stealer_assimilate",
            "life_stealer_assimilate_eject",
            "life_stealer_infest",
            "life_stealer_control",
            "life_stealer_consume",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Lifestealer",
        "attack_damage_base": 37,
        "movement_speed_max": 522,
        "base_attack_time": 1.85,
        "vulnerability_mag": 0.75
    }),
    lina: new Env({
        "str_gain": 1.5,
        "hp_regen": 0.25,
        "agi": 16,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 3.2,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 295,
        "int": 27,
        "mp_regen_base": 0.01,
        "agi_gain": 1.5,
        "str": 18,
        "abilities": [
            "lina_dragon_slave",
            "lina_light_strike_array",
            "lina_fiery_soul",
            "lina_laguna_blade",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Lina",
        "attack_damage_base": 22,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    lion: new Env({
        "str_gain": 1.7,
        "hp_regen": 0.25,
        "agi": 15,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 3,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 290,
        "int": 20,
        "mp_regen_base": 0.01,
        "agi_gain": 1.5,
        "str": 16,
        "abilities": [
            "lion_impale",
            "lion_voodoo",
            "lion_mana_drain",
            "lion_finger_of_death",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Lion",
        "attack_damage_base": 30,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    lone_druid: new Env({
        "str_gain": 2.1,
        "hp_regen": 0.5,
        "agi": 24,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 1.4,
        "primary_attribute": "agi",
        "is_melee": 0,
        "movement_speed": 325,
        "int": 13,
        "mp_regen_base": 0.01,
        "agi_gain": 2.7,
        "str": 17,
        "abilities": [
            "lone_druid_spirit_bear",
            "lone_druid_rabid",
            "lone_druid_savage_roar",
            "lone_druid_true_form_battle_cry",
            "lone_druid_true_form",
            "lone_druid_true_form_druid",
            "attribute_bonus"
        ],
        "armor": 0,
        "attack_speed_hero": 100,
        "name": "Lone Druid",
        "attack_damage_base": 24,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    luna: new Env({
        "str_gain": 2.2,
        "hp_regen": 0.25,
        "agi": 18,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 1.85,
        "primary_attribute": "agi",
        "is_melee": 0,
        "movement_speed": 335,
        "int": 16,
        "mp_regen_base": 0.01,
        "agi_gain": 3.3,
        "str": 15,
        "abilities": [
            "luna_lucent_beam",
            "luna_moon_glaive",
            "luna_lunar_blessing",
            "luna_eclipse",
            "attribute_bonus"
        ],
        "armor": 1,
        "attack_speed_hero": 100,
        "name": "Luna",
        "attack_damage_base": 29,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    lycan: new Env({
        "str_gain": 3,
        "hp_regen": 0.25,
        "agi": 16,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.55,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 305,
        "int": 17,
        "mp_regen_base": 0.01,
        "agi_gain": 1.9,
        "str": 22,
        "abilities": [
            "lycan_summon_wolves",
            "lycan_howl",
            "lycan_feral_impulse",
            "lycan_shapeshift",
            "attribute_bonus"
        ],
        "armor": 1,
        "attack_speed_hero": 100,
        "name": "Lycan",
        "attack_damage_base": 38.5,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    magnataur: new Env({
        "str_gain": 2.9,
        "hp_regen": 0.75,
        "agi": 15,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.65,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 315,
        "int": 19,
        "mp_regen_base": 0.01,
        "agi_gain": 2.5,
        "str": 21,
        "abilities": [
            "magnataur_shockwave",
            "magnataur_empower",
            "magnataur_skewer",
            "magnataur_reverse_polarity",
            "attribute_bonus"
        ],
        "armor": 2,
        "attack_speed_hero": 100,
        "name": "Magnus",
        "attack_damage_base": 38,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    medusa: new Env({
        "str_gain": 1.65,
        "hp_regen": 0.25,
        "agi": 20,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.1,
        "primary_attribute": "agi",
        "is_melee": 0,
        "movement_speed": 290,
        "int": 19,
        "mp_regen_base": 0.01,
        "agi_gain": 2.5,
        "str": 14,
        "abilities": [
            "medusa_split_shot",
            "medusa_mystic_snake",
            "medusa_mana_shield",
            "medusa_stone_gaze",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Medusa",
        "attack_damage_base": 27,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    meepo: new Env({
        "str_gain": 1.6,
        "hp_regen": 0.25,
        "agi": 23,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.6,
        "primary_attribute": "agi",
        "is_melee": 1,
        "movement_speed": 315,
        "int": 20,
        "mp_regen_base": 0.01,
        "agi_gain": 1.9,
        "str": 23,
        "abilities": [
            "meepo_earthbind",
            "meepo_poof",
            "meepo_geostrike",
            "meepo_divided_we_stand",
            "attribute_bonus"
        ],
        "armor": 1,
        "attack_speed_hero": 100,
        "name": "Meepo",
        "attack_damage_base": 23,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.65
    }),
    mirana: new Env({
        "str_gain": 1.85,
        "hp_regen": 0.25,
        "agi": 20,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 1.65,
        "primary_attribute": "agi",
        "is_melee": 0,
        "movement_speed": 300,
        "int": 17,
        "mp_regen_base": 0.01,
        "agi_gain": 3.3,
        "str": 17,
        "abilities": [
            "mirana_starfall",
            "mirana_arrow",
            "mirana_leap",
            "mirana_invis",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Mirana",
        "attack_damage_base": 23.5,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    morphling: new Env({
        "str_gain": 2,
        "hp_regen": 0.25,
        "agi": 24,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 1.5,
        "primary_attribute": "agi",
        "is_melee": 0,
        "movement_speed": 285,
        "int": 17,
        "mp_regen_base": 0.01,
        "agi_gain": 3.7,
        "str": 19,
        "abilities": [
            "morphling_waveform",
            "morphling_adaptive_strike",
            "morphling_morph_agi",
            "morphling_morph_str",
            "morphling_hybrid",
            "morphling_replicate",
            "morphling_morph",
            "morphling_morph_replicate",
            "attribute_bonus"
        ],
        "armor": -2,
        "attack_speed_hero": 100,
        "name": "Morphling",
        "attack_damage_base": 17.5,
        "movement_speed_max": 522,
        "base_attack_time": 1.6,
        "vulnerability_mag": 0.75
    }),
    naga_siren: new Env({
        "str_gain": 2.5,
        "hp_regen": 0.75,
        "agi": 21,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 2,
        "primary_attribute": "agi",
        "is_melee": 1,
        "movement_speed": 320,
        "int": 21,
        "mp_regen_base": 0.01,
        "agi_gain": 2.75,
        "str": 21,
        "abilities": [
            "naga_siren_mirror_image",
            "naga_siren_ensnare",
            "naga_siren_rip_tide",
            "naga_siren_song_of_the_siren",
            "naga_siren_song_of_the_siren_cancel",
            "attribute_bonus"
        ],
        "armor": 3,
        "attack_speed_hero": 100,
        "name": "Naga Siren",
        "attack_damage_base": 24,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    furion: new Env({
        "str_gain": 1.8,
        "hp_regen": 0.25,
        "agi": 18,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.9,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 295,
        "int": 25,
        "mp_regen_base": 0.01,
        "agi_gain": 1.9,
        "str": 19,
        "abilities": [
            "furion_sprout",
            "furion_teleportation",
            "furion_force_of_nature",
            "furion_wrath_of_nature",
            "attribute_bonus"
        ],
        "armor": 1,
        "attack_speed_hero": 100,
        "name": "Nature's Prophet",
        "attack_damage_base": 31,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    necrolyte: new Env({
        "str_gain": 2,
        "hp_regen": 0.25,
        "agi": 15,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.5,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 290,
        "int": 22,
        "mp_regen_base": 0.01,
        "agi_gain": 1.7,
        "str": 16,
        "abilities": [
            "necrolyte_death_pulse",
            "necrolyte_heartstopper_aura",
            "necrolyte_sadist",
            "necrolyte_reapers_scythe",
            "attribute_bonus"
        ],
        "armor": 1,
        "attack_speed_hero": 100,
        "name": "Necrophos",
        "attack_damage_base": 24,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    night_stalker: new Env({
        "str_gain": 2.8,
        "hp_regen": 2,
        "agi": 18,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.6,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 295,
        "int": 16,
        "mp_regen_base": 0.01,
        "agi_gain": 2.25,
        "str": 23,
        "abilities": [
            "night_stalker_void",
            "night_stalker_crippling_fear",
            "night_stalker_hunter_in_the_night",
            "night_stalker_darkness",
            "attribute_bonus"
        ],
        "armor": 3,
        "attack_speed_hero": 100,
        "name": "Night Stalker",
        "attack_damage_base": 40,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    nyx_assassin: new Env({
        "str_gain": 2,
        "hp_regen": 3.5,
        "agi": 19,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 2.1,
        "primary_attribute": "agi",
        "is_melee": 1,
        "movement_speed": 305,
        "int": 18,
        "mp_regen_base": 0.01,
        "agi_gain": 2.2,
        "str": 18,
        "abilities": [
            "nyx_assassin_impale",
            "nyx_assassin_mana_burn",
            "nyx_assassin_spiked_carapace",
            "nyx_assassin_burrow",
            "nyx_assassin_unburrow",
            "nyx_assassin_vendetta",
            "attribute_bonus"
        ],
        "armor": 1,
        "attack_speed_hero": 100,
        "name": "Nyx Assassin",
        "attack_damage_base": 32,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    ogre_magi: new Env({
        "str_gain": 3.2,
        "hp_regen": 3.5,
        "agi": 14,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 2.4,
        "primary_attribute": "int",
        "is_melee": 1,
        "movement_speed": 295,
        "int": 17,
        "mp_regen_base": 0.01,
        "agi_gain": 1.55,
        "str": 23,
        "abilities": [
            "ogre_magi_fireblast",
            "ogre_magi_ignite",
            "ogre_magi_bloodlust",
            "ogre_magi_unrefined_fireblast",
            "ogre_magi_multicast",
            "attribute_bonus"
        ],
        "armor": 6,
        "attack_speed_hero": 100,
        "name": "Ogre Magi",
        "attack_damage_base": 44,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    omniknight: new Env({
        "str_gain": 2.8,
        "hp_regen": 0.25,
        "agi": 15,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.8,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 305,
        "int": 17,
        "mp_regen_base": 0.01,
        "agi_gain": 1.75,
        "str": 22,
        "abilities": [
            "omniknight_purification",
            "omniknight_repel",
            "omniknight_degen_aura",
            "omniknight_guardian_angel",
            "attribute_bonus"
        ],
        "armor": 3,
        "attack_speed_hero": 100,
        "name": "Omniknight",
        "attack_damage_base": 36,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    oracle: new Env({
        "str_gain": 1.9,
        "hp_regen": 0.25,
        "agi": 15,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.9,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 305,
        "int": 23,
        "mp_regen_base": 0.01,
        "agi_gain": 1.7,
        "str": 18,
        "abilities": [
            "oracle_fortunes_end",
            "oracle_fates_edict",
            "oracle_purifying_flames",
            "oracle_false_promise",
            "attribute_bonus"
        ],
        "armor": 0,
        "attack_speed_hero": 100,
        "name": "Oracle",
        "attack_damage_base": 25,
        "movement_speed_max": 522,
        "base_attack_time": 1.4,
        "vulnerability_mag": 0.75
    }),
    obsidian_destroyer: new Env({
        "str_gain": 2.3,
        "hp_regen": 0.25,
        "agi": 24,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.7,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 315,
        "int": 26,
        "mp_regen_base": 0.01,
        "agi_gain": 2,
        "str": 19,
        "abilities": [
            "obsidian_destroyer_arcane_orb",
            "obsidian_destroyer_astral_imprisonment",
            "obsidian_destroyer_essence_aura",
            "obsidian_destroyer_sanity_eclipse",
            "attribute_bonus"
        ],
        "armor": 2,
        "attack_speed_hero": 100,
        "name": "Outworld Devourer",
        "attack_damage_base": 27.5,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    phantom_assassin: new Env({
        "str_gain": 1.85,
        "hp_regen": 0.25,
        "agi": 23,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.4,
        "primary_attribute": "agi",
        "is_melee": 1,
        "movement_speed": 310,
        "int": 15,
        "mp_regen_base": 0.01,
        "agi_gain": 3.15,
        "str": 20,
        "abilities": [
            "phantom_assassin_stifling_dagger",
            "phantom_assassin_phantom_strike",
            "phantom_assassin_blur",
            "phantom_assassin_coup_de_grace",
            "attribute_bonus"
        ],
        "armor": 1,
        "attack_speed_hero": 100,
        "name": "Phantom Assassin",
        "attack_damage_base": 24,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    phantom_lancer: new Env({
        "str_gain": 1.7,
        "hp_regen": 0.75,
        "agi": 29,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 2,
        "primary_attribute": "agi",
        "is_melee": 1,
        "movement_speed": 290,
        "int": 21,
        "mp_regen_base": 0.01,
        "agi_gain": 2.6,
        "str": 21,
        "abilities": [
            "phantom_lancer_spirit_lance",
            "phantom_lancer_doppelwalk",
            "phantom_lancer_phantom_edge",
            "phantom_lancer_juxtapose",
            "attribute_bonus"
        ],
        "armor": 0,
        "attack_speed_hero": 100,
        "name": "Phantom Lancer",
        "attack_damage_base": 33,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    phoenix: new Env({
        "str_gain": 2.9,
        "hp_regen": 0.25,
        "agi": 12,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 1.8,
        "primary_attribute": "str",
        "is_melee": 0,
        "movement_speed": 285,
        "int": 18,
        "mp_regen_base": 0.01,
        "agi_gain": 1.3,
        "str": 17,
        "abilities": [
            "phoenix_icarus_dive",
            "phoenix_fire_spirits",
            "phoenix_sun_ray",
            "phoenix_supernova",
            "phoenix_launch_fire_spirit",
            "phoenix_icarus_dive_stop",
            "phoenix_sun_ray_stop",
            "phoenix_sun_ray_toggle_move",
            "attribute_bonus"
        ],
        "armor": -2,
        "attack_speed_hero": 100,
        "name": "Phoenix",
        "attack_damage_base": 31,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    puck: new Env({
        "str_gain": 1.7,
        "hp_regen": 0.25,
        "agi": 22,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.4,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 295,
        "int": 25,
        "mp_regen_base": 0.01,
        "agi_gain": 1.7,
        "str": 15,
        "abilities": [
            "puck_illusory_orb",
            "puck_waning_rift",
            "puck_phase_shift",
            "puck_ethereal_jaunt",
            "puck_dream_coil",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Puck",
        "attack_damage_base": 27.5,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    pudge: new Env({
        "str_gain": 3.2,
        "hp_regen": 0.25,
        "agi": 14,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.5,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 285,
        "int": 14,
        "mp_regen_base": 0.01,
        "agi_gain": 1.5,
        "str": 25,
        "abilities": [
            "pudge_meat_hook",
            "pudge_rot",
            "pudge_flesh_heap",
            "pudge_dismember",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Pudge",
        "attack_damage_base": 30,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    pugna: new Env({
        "str_gain": 1.2,
        "hp_regen": 0.25,
        "agi": 16,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 4.5,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 330,
        "int": 26,
        "mp_regen_base": 0.01,
        "agi_gain": 1,
        "str": 17,
        "abilities": [
            "pugna_nether_blast",
            "pugna_decrepify",
            "pugna_nether_ward",
            "pugna_life_drain",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Pugna",
        "attack_damage_base": 23,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    queenofpain: new Env({
        "str_gain": 1.7,
        "hp_regen": 0.25,
        "agi": 18,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.5,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 295,
        "int": 24,
        "mp_regen_base": 0.01,
        "agi_gain": 2,
        "str": 16,
        "abilities": [
            "queenofpain_shadow_strike",
            "queenofpain_blink",
            "queenofpain_scream_of_pain",
            "queenofpain_sonic_wave",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Queen of Pain",
        "attack_damage_base": 29,
        "movement_speed_max": 522,
        "base_attack_time": 1.6,
        "vulnerability_mag": 0.75
    }),
    razor: new Env({
        "str_gain": 2.3,
        "hp_regen": 0.25,
        "agi": 22,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 1.8,
        "primary_attribute": "agi",
        "is_melee": 0,
        "movement_speed": 295,
        "int": 19,
        "mp_regen_base": 0.01,
        "agi_gain": 2,
        "str": 21,
        "abilities": [
            "razor_plasma_field",
            "razor_static_link",
            "razor_unstable_current",
            "razor_eye_of_the_storm",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Razor",
        "attack_damage_base": 24,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    riki: new Env({
        "str_gain": 1.6,
        "hp_regen": 0.25,
        "agi": 34,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.3,
        "primary_attribute": "agi",
        "is_melee": 1,
        "movement_speed": 290,
        "int": 14,
        "mp_regen_base": 0.01,
        "agi_gain": 2.2,
        "str": 17,
        "abilities": [
            "riki_smoke_screen",
            "riki_blink_strike",
            "riki_permanent_invisibility",
            "riki_tricks_of_the_trade",
            "attribute_bonus"
        ],
        "armor": 0,
        "attack_speed_hero": 100,
        "name": "Riki",
        "attack_damage_base": 6,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    rubick: new Env({
        "str_gain": 1.5,
        "hp_regen": 0.25,
        "agi": 14,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.4,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 290,
        "int": 27,
        "mp_regen_base": 0.01,
        "agi_gain": 1.6,
        "str": 19,
        "abilities": [
            "rubick_telekinesis",
            "rubick_telekinesis_land",
            "rubick_fade_bolt",
            "rubick_null_field",
            "rubick_spell_steal",
            "rubick_hidden1",
            "rubick_hidden2",
            "rubick_hidden3",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Rubick",
        "attack_damage_base": 22,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    sand_king: new Env({
        "str_gain": 2.6,
        "hp_regen": 0.25,
        "agi": 19,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.8,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 300,
        "int": 16,
        "mp_regen_base": 0.01,
        "agi_gain": 2.1,
        "str": 22,
        "abilities": [
            "sandking_burrowstrike",
            "sandking_sand_storm",
            "sandking_caustic_finale",
            "sandking_epicenter",
            "attribute_bonus"
        ],
        "armor": 0,
        "attack_speed_hero": 100,
        "name": "Sand King",
        "attack_damage_base": 33,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    shadow_demon: new Env({
        "str_gain": 1.9,
        "hp_regen": 0.25,
        "agi": 18,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.7,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 295,
        "int": 23,
        "mp_regen_base": 0.01,
        "agi_gain": 2.2,
        "str": 17,
        "abilities": [
            "shadow_demon_disruption",
            "shadow_demon_soul_catcher",
            "shadow_demon_shadow_poison",
            "shadow_demon_shadow_poison_release",
            "shadow_demon_demonic_purge",
            "attribute_bonus"
        ],
        "armor": 0,
        "attack_speed_hero": 100,
        "name": "Shadow Demon",
        "attack_damage_base": 29,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    nevermore: new Env({
        "str_gain": 2,
        "hp_regen": 0.5,
        "agi": 20,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2,
        "primary_attribute": "agi",
        "is_melee": 0,
        "movement_speed": 310,
        "int": 18,
        "mp_regen_base": 0.01,
        "agi_gain": 2.9,
        "str": 15,
        "abilities": [
            "nevermore_shadowraze1",
            "nevermore_shadowraze2",
            "nevermore_shadowraze3",
            "nevermore_necromastery",
            "nevermore_dark_lord",
            "nevermore_requiem",
            "attribute_bonus"
        ],
        "armor": -2,
        "attack_speed_hero": 100,
        "name": "Shadow Fiend",
        "attack_damage_base": 18,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    shadow_shaman: new Env({
        "str_gain": 1.8,
        "hp_regen": 0.25,
        "agi": 16,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 3,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 285,
        "int": 21,
        "mp_regen_base": 0.01,
        "agi_gain": 1.6,
        "str": 21,
        "abilities": [
            "shadow_shaman_ether_shock",
            "shadow_shaman_voodoo",
            "shadow_shaman_shackles",
            "shadow_shaman_mass_serpent_ward",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Shadow Shaman",
        "attack_damage_base": 29.5,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    silencer: new Env({
        "str_gain": 2.2,
        "hp_regen": 0.25,
        "agi": 22,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.5,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 295,
        "int": 27,
        "mp_regen_base": 0.01,
        "agi_gain": 3,
        "str": 17,
        "abilities": [
            "silencer_stolen_intelligence",
            "silencer_curse_of_the_silent",
            "silencer_glaives_of_wisdom",
            "silencer_last_word",
            "silencer_global_silence",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Silencer",
        "attack_damage_base": 23,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    skywrath_mage: new Env({
        "str_gain": 1.5,
        "hp_regen": 0.25,
        "agi": 13,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 3.6,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 325,
        "int": 27,
        "mp_regen_base": 0.01,
        "agi_gain": 0.8,
        "str": 19,
        "abilities": [
            "skywrath_mage_arcane_bolt",
            "skywrath_mage_concussive_shot",
            "skywrath_mage_ancient_seal",
            "skywrath_mage_mystic_flare",
            "attribute_bonus"
        ],
        "armor": -2,
        "attack_speed_hero": 100,
        "name": "Skywrath Mage",
        "attack_damage_base": 17,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    slardar: new Env({
        "str_gain": 2.8,
        "hp_regen": 0.25,
        "agi": 17,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.5,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 290,
        "int": 15,
        "mp_regen_base": 0.01,
        "agi_gain": 2.4,
        "str": 21,
        "abilities": [
            "slardar_sprint",
            "slardar_slithereen_crush",
            "slardar_bash",
            "slardar_amplify_damage",
            "attribute_bonus"
        ],
        "armor": 3,
        "attack_speed_hero": 100,
        "name": "Slardar",
        "attack_damage_base": 34,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    slark: new Env({
        "str_gain": 1.8,
        "hp_regen": 0.25,
        "agi": 21,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.9,
        "primary_attribute": "agi",
        "is_melee": 1,
        "movement_speed": 305,
        "int": 16,
        "mp_regen_base": 0.01,
        "agi_gain": 1.5,
        "str": 21,
        "abilities": [
            "slark_dark_pact",
            "slark_pounce",
            "slark_essence_shift",
            "slark_shadow_dance",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Slark",
        "attack_damage_base": 37,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    sniper: new Env({
        "str_gain": 1.7,
        "hp_regen": 0.25,
        "agi": 21,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.6,
        "primary_attribute": "agi",
        "is_melee": 0,
        "movement_speed": 290,
        "int": 15,
        "mp_regen_base": 0.01,
        "agi_gain": 2.5,
        "str": 16,
        "abilities": [
            "sniper_shrapnel",
            "sniper_headshot",
            "sniper_take_aim",
            "sniper_assassinate",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Sniper",
        "attack_damage_base": 18,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    spectre: new Env({
        "str_gain": 2,
        "hp_regen": 0.25,
        "agi": 23,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.9,
        "primary_attribute": "agi",
        "is_melee": 1,
        "movement_speed": 290,
        "int": 16,
        "mp_regen_base": 0.01,
        "agi_gain": 1.8,
        "str": 19,
        "abilities": [
            "spectre_spectral_dagger",
            "spectre_desolate",
            "spectre_dispersion",
            "spectre_reality",
            "spectre_haunt",
            "attribute_bonus"
        ],
        "armor": 0,
        "attack_speed_hero": 100,
        "name": "Spectre",
        "attack_damage_base": 25,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    spirit_breaker: new Env({
        "str_gain": 2.4,
        "hp_regen": 0.75,
        "agi": 17,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.8,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 290,
        "int": 14,
        "mp_regen_base": 0.01,
        "agi_gain": 1.7,
        "str": 29,
        "abilities": [
            "spirit_breaker_charge_of_darkness",
            "spirit_breaker_empowering_haste",
            "spirit_breaker_greater_bash",
            "spirit_breaker_nether_strike",
            "attribute_bonus"
        ],
        "armor": 3,
        "attack_speed_hero": 100,
        "name": "Spirit Breaker",
        "attack_damage_base": 36,
        "movement_speed_max": 522,
        "base_attack_time": 1.9,
        "vulnerability_mag": 0.75
    }),
    storm_spirit: new Env({
        "str_gain": 1.5,
        "hp_regen": 0.25,
        "agi": 22,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 3,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 285,
        "int": 24,
        "mp_regen_base": 0.01,
        "agi_gain": 1.8,
        "str": 19,
        "abilities": [
            "storm_spirit_static_remnant",
            "storm_spirit_electric_vortex",
            "storm_spirit_overload",
            "storm_spirit_ball_lightning",
            "attribute_bonus"
        ],
        "armor": 2,
        "attack_speed_hero": 100,
        "name": "Storm Spirit",
        "attack_damage_base": 27,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    sven: new Env({
        "str_gain": 2.7,
        "hp_regen": 0.25,
        "agi": 21,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.3,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 290,
        "int": 16,
        "mp_regen_base": 0.01,
        "agi_gain": 2,
        "str": 23,
        "abilities": [
            "sven_storm_bolt",
            "sven_great_cleave",
            "sven_warcry",
            "sven_gods_strength",
            "attribute_bonus"
        ],
        "armor": 2,
        "attack_speed_hero": 100,
        "name": "Sven",
        "attack_damage_base": 42,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    techies: new Env({
        "str_gain": 2,
        "hp_regen": 0.25,
        "agi": 14,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.9,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 270,
        "int": 22,
        "mp_regen_base": 0.02,
        "agi_gain": 1.3,
        "str": 17,
        "abilities": [
            "techies_land_mines",
            "techies_stasis_trap",
            "techies_suicide",
            "techies_focused_detonate",
            "techies_minefield_sign",
            "techies_remote_mines",
            "attribute_bonus"
        ],
        "armor": 5,
        "attack_speed_hero": 100,
        "name": "Techies",
        "attack_damage_base": 8,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    templar_assassin: new Env({
        "str_gain": 2.1,
        "hp_regen": 0.25,
        "agi": 23,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2,
        "primary_attribute": "agi",
        "is_melee": 0,
        "movement_speed": 305,
        "int": 20,
        "mp_regen_base": 0.01,
        "agi_gain": 2.7,
        "str": 18,
        "abilities": [
            "templar_assassin_refraction",
            "templar_assassin_meld",
            "templar_assassin_psi_blades",
            "templar_assassin_trap",
            "templar_assassin_psionic_trap",
            "attribute_bonus"
        ],
        "armor": 1,
        "attack_speed_hero": 100,
        "name": "Templar Assassin",
        "attack_damage_base": 33,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    terrorblade: new Env({
        "str_gain": 1.4,
        "hp_regen": 2,
        "agi": 22,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.75,
        "primary_attribute": "agi",
        "is_melee": 1,
        "movement_speed": 315,
        "int": 19,
        "mp_regen_base": 0.01,
        "agi_gain": 3.2,
        "str": 15,
        "abilities": [
            "terrorblade_reflection",
            "terrorblade_conjure_image",
            "terrorblade_metamorphosis",
            "terrorblade_sunder",
            "attribute_bonus"
        ],
        "armor": 7,
        "attack_speed_hero": 100,
        "name": "Terrorblade",
        "attack_damage_base": 29,
        "movement_speed_max": 522,
        "base_attack_time": 1.5,
        "vulnerability_mag": 0.75
    }),
    tidehunter: new Env({
        "str_gain": 3,
        "hp_regen": 0.25,
        "agi": 15,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.7,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 305,
        "int": 16,
        "mp_regen_base": 0.01,
        "agi_gain": 1.5,
        "str": 22,
        "abilities": [
            "tidehunter_gush",
            "tidehunter_kraken_shell",
            "tidehunter_anchor_smash",
            "tidehunter_ravage",
            "attribute_bonus"
        ],
        "armor": 1,
        "attack_speed_hero": 100,
        "name": "Tidehunter",
        "attack_damage_base": 28,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    shredder: new Env({
        "str_gain": 2.1,
        "hp_regen": 0.25,
        "agi": 16,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 2.4,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 290,
        "int": 21,
        "mp_regen_base": 0.01,
        "agi_gain": 1.3,
        "str": 22,
        "abilities": [
            "shredder_whirling_death",
            "shredder_timber_chain",
            "shredder_reactive_armor",
            "shredder_chakram_2",
            "shredder_return_chakram_2",
            "shredder_chakram",
            "shredder_return_chakram",
            "attribute_bonus"
        ],
        "armor": -2,
        "attack_speed_hero": 100,
        "name": "Timbersaw",
        "attack_damage_base": 28,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    tinker: new Env({
        "str_gain": 2,
        "hp_regen": 0.25,
        "agi": 13,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.2,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 305,
        "int": 30,
        "mp_regen_base": 0.01,
        "agi_gain": 1.2,
        "str": 17,
        "abilities": [
            "tinker_laser",
            "tinker_heat_seeking_missile",
            "tinker_march_of_the_machines",
            "tinker_rearm",
            "attribute_bonus"
        ],
        "armor": 2,
        "attack_speed_hero": 100,
        "name": "Tinker",
        "attack_damage_base": 25,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    tiny: new Env({
        "str_gain": 3,
        "hp_regen": 0.25,
        "agi": 9,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.6,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 285,
        "int": 17,
        "mp_regen_base": 0.01,
        "agi_gain": 0.9,
        "str": 26,
        "abilities": [
            "tiny_avalanche",
            "tiny_toss",
            "tiny_craggy_exterior",
            "tiny_grow",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Tiny",
        "attack_damage_base": 40,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    treant: new Env({
        "str_gain": 3.3,
        "hp_regen": 0.25,
        "agi": 15,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.8,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 300,
        "int": 17,
        "mp_regen_base": 0.01,
        "agi_gain": 2,
        "str": 25,
        "abilities": [
            "treant_natures_guise",
            "treant_leech_seed",
            "treant_living_armor",
            "treant_eyes_in_the_forest",
            "treant_overgrowth",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Treant Protector",
        "attack_damage_base": 66,
        "movement_speed_max": 522,
        "base_attack_time": 1.9,
        "vulnerability_mag": 0.75
    }),
    troll_warlord: new Env({
        "str_gain": 2.2,
        "hp_regen": 0.25,
        "agi": 21,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 1,
        "primary_attribute": "agi",
        "is_melee": 0,
        "movement_speed": 300,
        "int": 13,
        "mp_regen_base": 0.01,
        "agi_gain": 2.75,
        "str": 20,
        "abilities": [
            "troll_warlord_berserkers_rage",
            "troll_warlord_whirling_axes_ranged",
            "troll_warlord_whirling_axes_melee",
            "troll_warlord_fervor",
            "troll_warlord_battle_trance",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Troll Warlord",
        "attack_damage_base": 26,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    tusk: new Env({
        "str_gain": 2.3,
        "hp_regen": 0.25,
        "agi": 23,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.7,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 300,
        "int": 18,
        "mp_regen_base": 0.01,
        "agi_gain": 2.1,
        "str": 23,
        "abilities": [
            "tusk_ice_shards",
            "tusk_snowball",
            "tusk_frozen_sigil",
            "tusk_launch_snowball",
            "tusk_walrus_kick",
            "tusk_walrus_punch",
            "attribute_bonus"
        ],
        "armor": 0,
        "attack_speed_hero": 100,
        "name": "Tusk",
        "attack_damage_base": 29,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    undying: new Env({
        "str_gain": 2.1,
        "hp_regen": 0.25,
        "agi": 10,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 2.8,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 310,
        "int": 27,
        "mp_regen_base": 0.01,
        "agi_gain": 0.8,
        "str": 22,
        "abilities": [
            "undying_decay",
            "undying_soul_rip",
            "undying_tombstone",
            "undying_flesh_golem",
            "attribute_bonus"
        ],
        "armor": 2,
        "attack_speed_hero": 100,
        "name": "Undying",
        "attack_damage_base": 39,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    ursa: new Env({
        "str_gain": 2.7,
        "hp_regen": 0.75,
        "agi": 18,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.5,
        "primary_attribute": "agi",
        "is_melee": 1,
        "movement_speed": 310,
        "int": 16,
        "mp_regen_base": 0.01,
        "agi_gain": 2.1,
        "str": 23,
        "abilities": [
            "ursa_earthshock",
            "ursa_overpower",
            "ursa_fury_swipes",
            "ursa_enrage",
            "attribute_bonus"
        ],
        "armor": 3,
        "attack_speed_hero": 100,
        "name": "Ursa",
        "attack_damage_base": 29,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    vengefulspirit: new Env({
        "str_gain": 2.6,
        "hp_regen": 0.25,
        "agi": 27,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 1.5,
        "primary_attribute": "agi",
        "is_melee": 0,
        "movement_speed": 300,
        "int": 13,
        "mp_regen_base": 0.01,
        "agi_gain": 3.3,
        "str": 18,
        "abilities": [
            "vengefulspirit_magic_missile",
            "vengefulspirit_wave_of_terror",
            "vengefulspirit_command_aura",
            "vengefulspirit_nether_swap",
            "attribute_bonus"
        ],
        "armor": 0,
        "attack_speed_hero": 100,
        "name": "Vengeful Spirit",
        "attack_damage_base": 19,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    venomancer: new Env({
        "str_gain": 1.85,
        "hp_regen": 0.25,
        "agi": 22,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 1.8,
        "primary_attribute": "agi",
        "is_melee": 0,
        "movement_speed": 285,
        "int": 17,
        "mp_regen_base": 0.01,
        "agi_gain": 2.6,
        "str": 18,
        "abilities": [
            "venomancer_venomous_gale",
            "venomancer_poison_sting",
            "venomancer_plague_ward",
            "venomancer_poison_nova",
            "attribute_bonus"
        ],
        "armor": 0,
        "attack_speed_hero": 100,
        "name": "Venomancer",
        "attack_damage_base": 20,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    viper: new Env({
        "str_gain": 2.1,
        "hp_regen": 0.25,
        "agi": 21,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 1.8,
        "primary_attribute": "agi",
        "is_melee": 0,
        "movement_speed": 285,
        "int": 15,
        "mp_regen_base": 0.01,
        "agi_gain": 2.9,
        "str": 20,
        "abilities": [
            "viper_poison_attack",
            "viper_nethertoxin",
            "viper_corrosive_skin",
            "viper_viper_strike",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Viper",
        "attack_damage_base": 24,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    visage: new Env({
        "str_gain": 2.4,
        "hp_regen": 0.25,
        "agi": 11,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.5,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 285,
        "int": 24,
        "mp_regen_base": 0.01,
        "agi_gain": 1.3,
        "str": 22,
        "abilities": [
            "visage_grave_chill",
            "visage_soul_assumption",
            "visage_gravekeepers_cloak",
            "visage_summon_familiars",
            "attribute_bonus"
        ],
        "armor": -2,
        "attack_speed_hero": 100,
        "name": "Visage",
        "attack_damage_base": 29,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.9
    }),
    warlock: new Env({
        "str_gain": 2.5,
        "hp_regen": 0.25,
        "agi": 10,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.7,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 295,
        "int": 24,
        "mp_regen_base": 0.01,
        "agi_gain": 1,
        "str": 22,
        "abilities": [
            "warlock_fatal_bonds",
            "warlock_shadow_word",
            "warlock_upheaval",
            "warlock_rain_of_chaos",
            "attribute_bonus"
        ],
        "armor": 1,
        "attack_speed_hero": 100,
        "name": "Warlock",
        "attack_damage_base": 27,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    weaver: new Env({
        "str_gain": 1.5,
        "hp_regen": 0.25,
        "agi": 14,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 1.8,
        "primary_attribute": "agi",
        "is_melee": 0,
        "movement_speed": 290,
        "int": 15,
        "mp_regen_base": 0.01,
        "agi_gain": 2.5,
        "str": 15,
        "abilities": [
            "weaver_the_swarm",
            "weaver_shukuchi",
            "weaver_geminate_attack",
            "weaver_time_lapse",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Weaver",
        "attack_damage_base": 46,
        "movement_speed_max": 522,
        "base_attack_time": 1.8,
        "vulnerability_mag": 0.75
    }),
    windrunner: new Env({
        "str_gain": 2.5,
        "hp_regen": 0.25,
        "agi": 17,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.6,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 295,
        "int": 22,
        "mp_regen_base": 0.01,
        "agi_gain": 1.4,
        "str": 15,
        "abilities": [
            "windrunner_shackleshot",
            "windrunner_powershot",
            "windrunner_windrun",
            "windrunner_focusfire",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Windranger",
        "attack_damage_base": 28,
        "movement_speed_max": 522,
        "base_attack_time": 1.5,
        "vulnerability_mag": 0.75
    }),
    winter_wyvern: new Env({
        "str_gain": 2.1,
        "hp_regen": 0.25,
        "agi": 16,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 3.1,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 285,
        "int": 25,
        "mp_regen_base": 0.01,
        "agi_gain": 1.9,
        "str": 24,
        "abilities": [
            "winter_wyvern_arctic_burn",
            "winter_wyvern_splinter_blast",
            "winter_wyvern_cold_embrace",
            "winter_wyvern_winters_curse",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Winter Wyvern",
        "attack_damage_base": 16.5,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    witch_doctor: new Env({
        "str_gain": 1.8,
        "hp_regen": 0.25,
        "agi": 13,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.9,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 305,
        "int": 24,
        "mp_regen_base": 0.01,
        "agi_gain": 1.4,
        "str": 16,
        "abilities": [
            "witch_doctor_paralyzing_cask",
            "witch_doctor_voodoo_restoration",
            "witch_doctor_maledict",
            "witch_doctor_death_ward",
            "attribute_bonus"
        ],
        "armor": -1,
        "attack_speed_hero": 100,
        "name": "Witch Doctor",
        "attack_damage_base": 32,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    skeleton_king: new Env({
        "str_gain": 2.9,
        "hp_regen": 0.25,
        "agi": 18,
        "mp": 50,
        "is_ranged": 0,
        "hp": 200,
        "int_gain": 1.6,
        "primary_attribute": "str",
        "is_melee": 1,
        "movement_speed": 300,
        "int": 18,
        "mp_regen_base": 0.01,
        "agi_gain": 1.7,
        "str": 22,
        "abilities": [
            "skeleton_king_hellfire_blast",
            "skeleton_king_vampiric_aura",
            "skeleton_king_mortal_strike",
            "skeleton_king_reincarnation",
            "attribute_bonus"
        ],
        "armor": 0,
        "attack_speed_hero": 100,
        "name": "Wraith King",
        "attack_damage_base": 40,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    }),
    zuus: new Env({
        "str_gain": 2.3,
        "hp_regen": 0.25,
        "agi": 11,
        "mp": 50,
        "is_ranged": 1,
        "hp": 200,
        "int_gain": 2.7,
        "primary_attribute": "int",
        "is_melee": 0,
        "movement_speed": 295,
        "int": 20,
        "mp_regen_base": 0.01,
        "agi_gain": 1.2,
        "str": 19,
        "abilities": [
            "zuus_arc_lightning",
            "zuus_lightning_bolt",
            "zuus_static_field",
            "zuus_thundergods_wrath",
            "attribute_bonus"
        ],
        "armor": 0,
        "attack_speed_hero": 100,
        "name": "Zeus",
        "attack_damage_base": 25,
        "movement_speed_max": 522,
        "base_attack_time": 1.7,
        "vulnerability_mag": 0.75
    })
};